[build]
publish = "exampleSite/public"
command = "cd exampleSite && hugo --themesDir ../.."
[build.environment]
HUGO_VERSION = "0.78.2"
HUGO_THEME = "repo"
HUGO_BASEURL = "https://loveit.netlify.app"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
